/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author user
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihanHobi = new javax.swing.JCheckBox();
        PilihanJurusan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblAbsen = new javax.swing.JLabel();
        lblJurusan = new javax.swing.JLabel();
        Hobi = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtAbsen = new javax.swing.JTextField();
        TKJ = new javax.swing.JRadioButton();
        RPL = new javax.swing.JRadioButton();
        futsal = new javax.swing.JCheckBox();
        volly = new javax.swing.JCheckBox();
        Basket = new javax.swing.JCheckBox();
        Metic = new javax.swing.JCheckBox();
        FiberOptic = new javax.swing.JCheckBox();
        Robotic = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        pilihanHobi.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("BIODATA");

        lblNama.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNama.setForeground(new java.awt.Color(0, 0, 0));
        lblNama.setText("Nama");

        lblAbsen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAbsen.setForeground(new java.awt.Color(0, 0, 0));
        lblAbsen.setText("Absen");

        lblJurusan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJurusan.setForeground(new java.awt.Color(0, 0, 0));
        lblJurusan.setText("Jurusan");

        Hobi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Hobi.setForeground(new java.awt.Color(0, 0, 0));
        Hobi.setText("Hobi");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        PilihanJurusan.add(TKJ);
        TKJ.setText("TKJ (Teknik Komputer Jaringan)");

        PilihanJurusan.add(RPL);
        RPL.setText("RPL (Rekayasa Perangkat Lunak)");
        RPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPLActionPerformed(evt);
            }
        });

        futsal.setText("Futsal");

        volly.setText("Volly");

        Basket.setText("Basket");

        Metic.setText("Metic");

        FiberOptic.setText("Fiber Optic");

        Robotic.setText("Robotic");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Hasil ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnSubmit)
                                .addGap(34, 34, 34)
                                .addComponent(btnRemove)
                                .addGap(46, 46, 46)
                                .addComponent(btnExit))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNama)
                            .addComponent(lblAbsen)
                            .addComponent(lblJurusan)
                            .addComponent(Hobi))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNama)
                                .addComponent(txtAbsen)
                                .addComponent(RPL))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TKJ)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(futsal)
                                        .addComponent(volly)
                                        .addComponent(FiberOptic))
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Metic)
                                        .addComponent(Basket)
                                        .addComponent(Robotic)))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNama)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAbsen)
                            .addComponent(txtAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblJurusan))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RPL)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TKJ)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hobi)
                            .addComponent(futsal))
                        .addGap(18, 18, 18)
                        .addComponent(volly)
                        .addGap(18, 18, 18)
                        .addComponent(FiberOptic))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Basket)
                        .addGap(18, 18, 18)
                        .addComponent(Metic)
                        .addGap(18, 18, 18)
                        .addComponent(Robotic)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnRemove)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void RPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RPLActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String Nama = txtNama.getText();
        String Absen = txtAbsen.getText();
        String Jurusan;
        String hobi = null ;
        
        if(RPL.isSelected())
            Jurusan = "RPL (Rekayasa Perangkat Lunak)";
        else if(TKJ.isSelected())
            Jurusan = "TKJ (Teknik Komputer dan Jaringan)";
        else
            Jurusan = " ";
        
         if(futsal.isSelected())
            hobi =futsal.getText()+" ";
         if(volly.isSelected())
            hobi =volly.getText()+" ";
         if(FiberOptic.isSelected())
            hobi =FiberOptic.getText()+" ";
         if(Basket.isSelected())
            hobi =Basket.getText()+" ";
         if(Metic.isSelected())
            hobi =Metic.getText()+" ";
         if(Robotic.isSelected())
            hobi =Robotic.getText()+" ";
         hasil.setText("Nama     : "+Nama+
                     "\nAbsen     : "+Absen+
                     "\nJurusan  : "+Jurusan+
                     "\nHobi        : "+hobi);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        txtNama.setText("");
        txtAbsen.setText("");
        PilihanJurusan.clearSelection();
        hasil.setText("");
        futsal.setSelected(false);
        volly.setSelected(false);
        FiberOptic.setSelected(false);
        Basket.setSelected(false);
        Metic.setSelected(false);
        Robotic.setSelected(false);
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Basket;
    private javax.swing.JCheckBox FiberOptic;
    private javax.swing.JLabel Hobi;
    private javax.swing.JCheckBox Metic;
    private javax.swing.ButtonGroup PilihanJurusan;
    private javax.swing.JRadioButton RPL;
    private javax.swing.JCheckBox Robotic;
    private javax.swing.JRadioButton TKJ;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox futsal;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAbsen;
    private javax.swing.JLabel lblJurusan;
    private javax.swing.JLabel lblNama;
    private javax.swing.JCheckBox pilihanHobi;
    private javax.swing.JTextField txtAbsen;
    private javax.swing.JTextField txtNama;
    private javax.swing.JCheckBox volly;
    // End of variables declaration//GEN-END:variables
}
