/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Kalkulator extends javax.swing.JFrame {

String a ="";
double b, a1, a2;
int pilih;
int persent;

    public Kalkulator() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        satu = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        tujuh = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        nol = new javax.swing.JButton();
        titik = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        CE = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        samaDengan = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        akar = new javax.swing.JButton();
        seperX = new javax.swing.JButton();
        kuadrat = new javax.swing.JButton();
        Hasil = new javax.swing.JTextField();
        ats = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        h = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ats1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        getContentPane().setLayout(null);

        satu.setBackground(new java.awt.Color(51, 153, 255));
        satu.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        satu.setText("1");
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        getContentPane().add(satu);
        satu.setBounds(20, 250, 70, 70);

        dua.setBackground(new java.awt.Color(51, 153, 255));
        dua.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        dua.setText("2");
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        getContentPane().add(dua);
        dua.setBounds(100, 250, 70, 70);

        tiga.setBackground(new java.awt.Color(51, 153, 255));
        tiga.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        tiga.setText("3");
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        getContentPane().add(tiga);
        tiga.setBounds(180, 250, 70, 70);

        empat.setBackground(new java.awt.Color(51, 153, 255));
        empat.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        empat.setText("4");
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });
        getContentPane().add(empat);
        empat.setBounds(20, 330, 70, 70);

        lima.setBackground(new java.awt.Color(51, 153, 255));
        lima.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lima.setText("5");
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });
        getContentPane().add(lima);
        lima.setBounds(100, 330, 70, 70);

        enam.setBackground(new java.awt.Color(51, 153, 255));
        enam.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        enam.setText("6");
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });
        getContentPane().add(enam);
        enam.setBounds(180, 330, 70, 70);

        tujuh.setBackground(new java.awt.Color(51, 153, 255));
        tujuh.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        tujuh.setText("7");
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });
        getContentPane().add(tujuh);
        tujuh.setBounds(20, 410, 70, 70);

        delapan.setBackground(new java.awt.Color(51, 153, 255));
        delapan.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        delapan.setText("8");
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });
        getContentPane().add(delapan);
        delapan.setBounds(100, 410, 70, 70);

        sembilan.setBackground(new java.awt.Color(51, 153, 255));
        sembilan.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        sembilan.setText("9");
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });
        getContentPane().add(sembilan);
        sembilan.setBounds(180, 410, 70, 70);

        nol.setBackground(new java.awt.Color(51, 153, 255));
        nol.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        nol.setText("0");
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        getContentPane().add(nol);
        nol.setBounds(20, 490, 150, 70);

        titik.setBackground(new java.awt.Color(0, 51, 204));
        titik.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        titik.setText(".");
        titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikActionPerformed(evt);
            }
        });
        getContentPane().add(titik);
        titik.setBounds(180, 490, 70, 70);

        clear.setBackground(new java.awt.Color(0, 0, 204));
        clear.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(20, 170, 70, 70);

        CE.setBackground(new java.awt.Color(0, 51, 204));
        CE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CE.setText("Mod");
        getContentPane().add(CE);
        CE.setBounds(100, 170, 70, 70);

        bagi.setBackground(new java.awt.Color(0, 51, 204));
        bagi.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        getContentPane().add(bagi);
        bagi.setBounds(340, 250, 70, 70);

        kali.setBackground(new java.awt.Color(0, 51, 204));
        kali.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        kali.setText("X");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        getContentPane().add(kali);
        kali.setBounds(260, 250, 70, 70);

        kurang.setBackground(new java.awt.Color(0, 51, 204));
        kurang.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        getContentPane().add(kurang);
        kurang.setBounds(260, 330, 70, 70);

        tambah.setBackground(new java.awt.Color(0, 51, 204));
        tambah.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(260, 410, 70, 70);

        samaDengan.setBackground(new java.awt.Color(0, 51, 204));
        samaDengan.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        samaDengan.setText("=");
        samaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samaDenganActionPerformed(evt);
            }
        });
        getContentPane().add(samaDengan);
        samaDengan.setBounds(260, 490, 70, 70);

        persen.setBackground(new java.awt.Color(0, 51, 204));
        persen.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        getContentPane().add(persen);
        persen.setBounds(340, 490, 70, 70);

        akar.setBackground(new java.awt.Color(0, 51, 204));
        akar.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        akar.setText("√");
        akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akarActionPerformed(evt);
            }
        });
        getContentPane().add(akar);
        akar.setBounds(340, 410, 70, 70);

        seperX.setBackground(new java.awt.Color(0, 51, 204));
        seperX.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        seperX.setText("1/x");
        seperX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seperXActionPerformed(evt);
            }
        });
        getContentPane().add(seperX);
        seperX.setBounds(340, 330, 70, 70);

        kuadrat.setBackground(new java.awt.Color(0, 51, 204));
        kuadrat.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        kuadrat.setText(" x²");
        kuadrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuadratActionPerformed(evt);
            }
        });
        getContentPane().add(kuadrat);
        kuadrat.setBounds(180, 170, 70, 70);

        Hasil.setBackground(new java.awt.Color(153, 255, 255));
        Hasil.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        Hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilActionPerformed(evt);
            }
        });
        getContentPane().add(Hasil);
        Hasil.setBounds(20, 40, 390, 120);

        ats.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(ats);
        ats.setBounds(20, 10, 150, 30);

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jButton1.setText("←");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 170, 150, 70);

        h.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\Saved Pictures\\3556273a597fb81.jpg")); // NOI18N
        h.setText("jLabel1");
        getContentPane().add(h);
        h.setBounds(0, 0, 450, 320);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\Saved Pictures\\3556273a597fb81.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-6, 315, 460, 290);

        ats1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(ats1);
        ats1.setBounds(20, 10, 150, 30);

        setSize(new java.awt.Dimension(449, 636));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
Hasil.setText("");
ats.setText("");
a1= 0.0;
a2=0.0;
b=0.0;
a=" ";

    }//GEN-LAST:event_clearActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
a1=Double.parseDouble(a);
Hasil.setText("*");
ats.setText(a1+" x ");
a="";
pilih=3;        // TODO add your handling code here:
        
    }//GEN-LAST:event_kaliActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        // TODO add your handling code here:
         a += "1";
        Hasil.setText(a);
    }//GEN-LAST:event_satuActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        // TODO add your handling code here:
         a += "2";
        Hasil.setText(a);
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        // TODO add your handling code here:
         a += "3";
        Hasil.setText(a);
    }//GEN-LAST:event_tigaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        // TODO add your handling code here:
         a += "4";
        Hasil.setText(a);
    }//GEN-LAST:event_empatActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
      a += "5";
        Hasil.setText(a);
    }//GEN-LAST:event_limaActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
     a += "6";
        Hasil.setText(a);
    }//GEN-LAST:event_enamActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        a += "7";
        Hasil.setText(a);
    }//GEN-LAST:event_tujuhActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
     a += "8";
        Hasil.setText(a);
    }//GEN-LAST:event_delapanActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
      a  += "9";
        Hasil.setText(a);        // TODO add your handling code here:
    }//GEN-LAST:event_sembilanActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
       a += "0";
        Hasil.setText(a); // TODO add your handling code here:
    }//GEN-LAST:event_nolActionPerformed

    private void HasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilActionPerformed

    private void titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikActionPerformed
     a += ".";
        Hasil.setText(a);        // TODO add your handling code here:
    }//GEN-LAST:event_titikActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
a1=Double.parseDouble(a);
ats.setText(a1+"+");
Hasil.setText("+");
a="";
pilih=1;// TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
a1=Double.parseDouble(a);
ats.setText(a1+"-");
Hasil.setText("-");
a="";
pilih=2;        // TODO add your handling code here:
    }//GEN-LAST:event_kurangActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
a1=Double.parseDouble(a);
ats.setText(a1+"/");
Hasil.setText("/");
a="";
pilih=4;        // TODO add your handling code here:
    }//GEN-LAST:event_bagiActionPerformed

    private void samaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samaDenganActionPerformed
switch(pilih){
        case 1:
            a2=Double.parseDouble(a);
            b = a1 + a2;
            a = Double.toString(b);
            Hasil.setText(a);
            ats.setText(a1+" + "+a2+" = ");
            break;
        case 2:
            a2=Double.parseDouble(a);
            b = a1 - a2;
            a = Double.toString(b);
            Hasil.setText(a);
            ats.setText(a1+" - "+a2+" = ");
            break;
        case 3:
            a2=Double.parseDouble(a);
            b = a1 * a2;
            a = Double.toString(b);
            Hasil.setText(a);
            ats.setText(a1+" x "+a2+" = ");
            break;
        case 4:
            a2=Double.parseDouble(a);
            b = a1 / a2;
            a = Double.toString(b);
            Hasil.setText(a);
            ats.setText(a1+" / "+a2+" = ");
            break; 
       /* case 5:
           
            b = a1 / 100;
            a = Double.toString(b);
            Hasil.setText(""+b);
            ats.setText(a1+" % "+a2+" = ");
            break;/*/ 
        case 6:
            a2=Double.parseDouble(a);
            b = Math.pow(a1, a2);
            a = Double.toString(b);
            Hasil.setText(a);
            ats.setText(a1+" ^ "+a2+" = ");
            break; 
        /*case 7:
           
            b = Math.sqrt(a1);
            a = Double.toString(b);
            Hasil.setText(a);
            ats.setText(" √ "+a1+" = ");
            break;/*/
    }        
    }//GEN-LAST:event_samaDenganActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
a1=Double.parseDouble(a);
b = a1 / 100;
a = Double.toString(b);
Hasil.setText(""+b);
ats.setText(a1+" % "+a2+" = ");
    }//GEN-LAST:event_persenActionPerformed

    private void akarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akarActionPerformed
a1 = Double.parseDouble(a);
b = Math.sqrt(a1);
a = Double.toString(b);
Hasil.setText(a);
ats.setText(" √ ("+a1+")");      
    }//GEN-LAST:event_akarActionPerformed

    private void kuadratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuadratActionPerformed
a1=Double.parseDouble(a);
Hasil.setText("^");
ats.setText(a1+"^");
a="";
pilih=6;      // TODO add your handling code here:
    }//GEN-LAST:event_kuadratActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 a = a.substring(0, a.length()-1);
 Hasil.setText(a);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void seperXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seperXActionPerformed
a1=Double.parseDouble(a);
b = 1 / a1;
a = Double.toString(b);
Hasil.setText(""+b);
ats.setText(" 1 / ("+a1+")");
    }//GEN-LAST:event_seperXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Kalkulator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CE;
    private javax.swing.JTextField Hasil;
    private javax.swing.JButton akar;
    private javax.swing.JLabel ats;
    private javax.swing.JLabel ats1;
    private javax.swing.JButton bagi;
    private javax.swing.JButton clear;
    private javax.swing.JButton delapan;
    private javax.swing.JButton dua;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private javax.swing.JLabel h;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton kali;
    private javax.swing.JButton kuadrat;
    private javax.swing.JButton kurang;
    private javax.swing.JButton lima;
    private javax.swing.JButton nol;
    private javax.swing.JButton persen;
    private javax.swing.JButton samaDengan;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton seperX;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tiga;
    private javax.swing.JButton titik;
    private javax.swing.JButton tujuh;
    // End of variables declaration//GEN-END:variables
}
